### ISSUE TITLE
Raspberry Pi 3 with I2C Adapter IO Error 5

### ISSUE THREAD

**Issue by ericgcoker** [ControlEverythingCommunity/ADC121C_MQ9#1]
The following code is giving me the following error. 
` data = bus.read_i2c_block_data(0x50, 0x00, 2)`
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/smbus/util.py", line 59, in validator
    return fn(*args, **kwdefaults)
  File "/usr/local/lib/python2.7/dist-packages/smbus/smbus.py", line 258, in read_i2c_block_data
    raise IOError(ffi.errno)
IOError: 5
```

I'm also not detecting anything with 
`sudo i2cdetect 1`
, although I have a red light on the MQ9 Sensor, as well as the red power light on the I2C Adapter on top of the Pi.
Is my sensor shot, or am I not receiving enough power?

**Comment by zaphod-42** [comment]
Have you enabled the I2C Bus on the Pi? It is not enabled by default and that is usually the cause of these types of issues.
